### ISSUE TITLE
problem in extract files

### ISSUE THREAD

**Issue by ghost** [Joshuajrodrigues/manga2epub4kindle#2]
⠋ Extracting files...Unhandled rejection Error: invalid signature: 0x21726152
    at /usr/lib/node_modules/manga2epub4kindle/node_modules/unzipper/lib/parse.js:66:26
    at tryCatcher (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/manga2epub4kindle/node_modules/bluebird/js/release/async.js:17:14)
    at process.processImmediate (node:internal/timers:471:21)

⠧ Extracting files...

hi there!!! i have this issue in the app... i use arch linux 

thank for all!!!

**Comment by Joshuajrodrigues** [comment]
Heyy, let me see what i can do. Can you provide me some more info on how this occured ?

**Comment by Joshuajrodrigues** [comment]
Also what type of file do you have ? Is it a cbz or cbr ?

**Comment by ghost** [comment]
thank you for the reply..... 

https://imgur.com/a/KXbuPnq

Here is the problem in 2 different computers ... in my case I install the program with NPM on a computer with Arch Linux and run the program (Screenshot 2).

in my case i use cbr files.

Could it be that the program depends on Kindlegen?

**Comment by Joshuajrodrigues** [comment]
Na it doesnt need kindle gen. Its the unzipper. Node seems to have pretty abysmal solutions for an extracter. Ill look into it

**Comment by ghost** [comment]
Thank you very much for responding so quickly...

I participate with a group of friends to convert and share mangas among us, and when I saw your solution we love it.

Thank you very much for creating and sharing it !!!

**Comment by Joshuajrodrigues** [comment]
Say could you do me a favor and extract your cbr/cbz file manually?


Incase you need instructions basically :

Rename your cbz/cbr file with the .zip extention

So if you have jojo.cbz rename it to jojo.zip.

Then open the zip folder. Or extract it to a new folder and let me know whats inside. Is it a collection of images, is there any file in there thats not an image by any chance ?

Reason being i can't replicate it easily. Tho the issue does exist on some system. Thinking of patching it manually.

**Comment by Joshuajrodrigues** [comment]
another thing, once you rename it run unzip -t file.zip, file .zip being your manga name so jojo.zip. this will check integrity of your zip file

**Comment by ghost** [comment]
the output to unzip -t file.zip and the  cbr file unzipet.  https://imgur.com/a/ClFNMwy

**Comment by Joshuajrodrigues** [comment]
nice, cbr file unziped, the files inside are they zip files again or just folders ?

**Comment by ghost** [comment]
just folders

**Comment by Joshuajrodrigues** [comment]
alright so here's the issue, Usually cbr/cbz files are just zip files that have images in them. I did encounter one bleach volume that had a zip file inside a zip file, manga2epub4kindle. can handle those too. Folders in zip isnt handled, but im willing to now, tho itll take a bit of time. But mostly within this week.

In the mean time if your in a hurry all you'll mostly have to do is open those folders copy all images out to parent delete the folders after and then rename back to cbr cbz. Ik its awful lot to do.

Also would be really helpful if you could link me to where you got your jojo files from. I can use it for my testing and also would like to get into jojoj

**Comment by ghost** [comment]
here is the link https://www.mar9celo3.com/2019/05/Descargar-JoJo-Parte-8-JoJolion.html?m=1

thanks for the reply and the time for fix this... i can wait for the news.

**Comment by h0l0cr0n** [comment]
![Untitled](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/bb4f98cd-40ff-42c6-889f-e2c1f6a3db6b)

Hey guys, am i missing something. trying to get this to work :) tried other cbz's too.
the cbz files only have png and jpg inside of them

what you made here is very cool

**Comment by Joshuajrodrigues** [comment]
> ![Untitled](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/bb4f98cd-40ff-42c6-889f-e2c1f6a3db6b)
> 
> Hey guys, am i missing something. trying to get this to work :) tried other cbz's too.
> the cbz files only have png and jpg inside of them
> 
> what you made here is very cool

Can you try with just 1 file ? Im currently in the process of rebuilding this since most of its dependencies are depreciated. Which is causing issues. Mostly its the unzip that either fails or corrupts the files. 

Also if possible do share me a link to a sample of what you're trying to convert

**Comment by Joshuajrodrigues** [comment]
@h0l0cr0n 

Use node 16, seems like this script breaks in node 18. Ill have to check it out, but it works fine on 16

**Comment by h0l0cr0n** [comment]
thnx m8. :)

**Comment by h0l0cr0n** [comment]
Tried it and it works, only amazon screwing up at their side. caus they keep inserinting white pages (send to kindle) (-.- sometimes even 3 in a row), every 3/5 pages or so. or do you use anything else to import to kindle scribe? its such a good device but i wish you could just drag and drop your epubs on it. (when uploaded the aszw3 file to kalibre, it shows no blank pages but on scribe it does x_X)

**Comment by h0l0cr0n** [comment]
![32](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/f324a5a1-b6e0-451a-b86e-353d59060714)
![33](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/05fefddd-e692-4deb-b8d3-f6d07371f2f7)
![34](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/00b31297-2398-4699-a57e-4281cd4638b3)
![35](https://github.com/Joshuajrodrigues/manga2epub4kindle/assets/47682511/a170cf0b-f2f7-4106-970b-f2d88fc93506)

Like this =(

**Comment by TinoCle** [comment]
Fails with Node 16 for me

```bash
❯ nvm use 16
Now using node v16.20.2 (npm v8.19.4)
❯ npm i manga2epub4kindle
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated fstream@1.0.12: This package is no longer supported.

added 223 packages, and audited 224 packages in 14s

51 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
❯ npx manga2epub4kindle
Welcome to Manga2epub4kindle 🍺

    Make sure you ran me in a folder full of cbz/cbr files.

Found 3 valid file/s.
? Select files to process Spy Family - Tomo 01 (#001-005).cbr
? Enter series name Default Series
? Enter author name Default Author
? Enter Genre name
? Enter publisher name Default Publisher
? Select your kindle Kindle Paperwhite 3/4/Voyage/Oasis
? Select start index for series (Volume number starts from) 0
? Would you like to save this metadata for future use ? Yes
⠋ Extracting files...Unhandled rejection Error: invalid signature: 0x21726152
    at /Users/tino/Downloads/SpyXFamily/node_modules/unzipper/lib/parse.js:70:26
    at tryCatcher (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tino/Downloads/SpyXFamily/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by Joshuajrodrigues** [comment]
I'm working on updating this repo. Clearly it's been giving a lot of issues. Id advice consider using the kindle comic converter as it now supports all the things this library was intended for.

Smaller size and faster conversations. 

The future looks bleek for this library tho I'm open to contributions
